### ISSUE TITLE
Morning session review

### ISSUE THREAD

**Issue by myelin0** [VTY1999/Portfolio-setup-and-mobile-version-skeleton#12]
Hi Francis! 👋 Very Nice work with your Portfolio, but you should look into some minor issues:
-Please deploy your page online so all the changes created with Javascript can be seen.
-Your mobile version is missing 4 cards. It is optional to create those if you want to show off all your works and not just 2 of them.

**Comment by BereketRetta** [comment]
Hi Francis, Excellent code structure and nice work with your portfolio.
The one thing I advise you on doing is that you should structure your JS file according to the common way of writing for instance you should first define your variables and then write the function at the bottom (in an alphabetical order preferably)

**Comment by VTY1999** [comment]
I have fixed issues.
